# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:  
  workflow_call:
    inputs:
      analysis:
        description: Whether to run static analysis
        type: boolean
        required: false
        default: false
      verbose:
        description: Whether to run mvn commands in verbose mode
        type: boolean
        required: false
        default: false
          
jobs:
  maven-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: CI
    continue-on-error: false
    env:
      SERVER_WEBSITE_USER: ${{ secrets.SERVER_WEBSITE_USER }}
      SERVER_WEBSITE_PASSWORD: ${{ secrets.SERVER_WEBSITE_PASSWORD }}
      SERVER_MAVEN_REPO_USER: ${{ secrets.SERVER_MAVEN_REPO_USER }}
      SERVER_MAVEN_REPO_PASSWORD: ${{ secrets.SERVER_MAVEN_REPO_PASSWORD }}
      SERVER_SONATYPE_NEXUS_SNAPSHOTS_USER: ${{ secrets.SERVER_SONATYPE_NEXUS_SNAPSHOTS_USER }}
      SERVER_SONATYPE_NEXUS_SNAPSHOTS_PASSWORD: ${{ secrets.SERVER_SONATYPE_NEXUS_SNAPSHOTS_PASSWORD }}
      SERVER_SONATYPE_NEXUS_STAGING_USER: ${{ secrets.SERVER_SONATYPE_NEXUS_STAGING_USER }}
      SERVER_SONATYPE_NEXUS_STAGING_PASSWORD: ${{ secrets.SERVER_SONATYPE_NEXUS_STAGING_PASSWORD }}
      SERVER_SCM_USER: ${{ secrets.SERVER_SCM_USER }}
      SERVER_SCM_PASSWORD: ${{ secrets.SERVER_SCM_PASSWORD }}
      SERVER_BUILD_REPO_USER: ${{ secrets.SERVER_BUILD_REPO_USER }}
      SERVER_BUILD_REPO_PASSWORD: ${{ secrets.SERVER_BUILD_REPO_PASSWORD }}
      ARTIFACTORY_REPO_URL: ${{ secrets.ARTIFACTORY_REPO_URL }}
      SERVER_SCM_ID: ${{ secrets.SERVER_SCM_ID }}
      
    steps:
    - name: Checkout build repo
      uses: actions/checkout@v3
      
    - name: Extract owner
      shell: bash
      run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%/*})"
      id: extract_owner
      
    - name: Checkout config repo
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.extract_owner.outputs.owner }}/jsdn-devops-config
        ref: main
        token: ${{ secrets.GH_PAT }}
        path: devops-config
        
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '7'
        cache: 'maven'
    
    - name: Setup maven
      uses: stCarolas/setup-maven@v4.4
      with:
          maven-version: 3.6.3
                
    - name: Copy settings.xml
      run: |
       cp devops-config/.m2/settings.xml ~/.m2/settings.xml
        
    - name: Add hosts to /etc/hosts
      run: |
       sudo echo "18.235.126.9 mavenrepo.jstpl.com" | sudo tee -a /etc/hosts
       
    - name: "Set mvn flags"
      id: mvn_options
      env:
        VERBOSE_FLAG: ${{ inputs.verbose}}
      run: |
        flag='-q'
        if ${VERBOSE_FLAG} == true; then
           flag='-X'
        fi
        echo "##[set-output name=flag;]$(echo $flag)"
       
    - name: Static code analysis
      if: ${{ inputs.analysis == true }}
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'devops-config/pmd/rules.xml'
      
    - name: Build
      run: |
       mvn clean install ${{ steps.mvn_options.outputs.flag }} 
   
    - name: Get publish settings
      id: publish_settings
      run: |
        project_verison=$(grep "<version>" pom.xml | head -1 | sed -e 's/^ *<version>\(.*\)<\/version> *$/\1/')
        echo "Retrived project verison as $project_verison"
        id='releases'
        repo='libs-release'
        if [[ $project_verison =~ "SNAPSHOT" ]]; then
            id='snapshots'
            repo='libs-snapshot'
        fi
        echo "##[set-output name=id;]$(echo $id)"
        echo "##[set-output name=repo;]$(echo $repo)"
        
    - name: Publish
      run: | 
        echo "Publish using id as ${{ steps.publish_settings.outputs.id }} and repo as ${{ steps.publish_settings.outputs.repo }}"
        mvn deploy -DaltDeploymentRepository=${{ steps.publish_settings.outputs.id }}::default::http://mavenrepo.jstpl.com/artifactory/${{ steps.publish_settings.outputs.repo }} ${{ steps.mvn_options.outputs.flag }}
